[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "git_calendar"
authors = [{name = "Richard Darst"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "yaml2ics",
    "jinja2",
    "mutt-ics",
    "pyyaml",
]

[project.scripts]
git-calendar = "git_calendar.build:main"

[project.urls]
Home = "https://github.com/coderefinery/git-calendar"
